repos:
  - repo: local
    hooks:
      - id: run-make-test
        name: Run make test
        entry: make test
        language: system
        pass_filenames: false

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [
          '--skip=docs/Gemfile.lock,tests/unit/gpt2-merges.txt,tests/unit/gpt2-vocab.json',
          '--ignore-regex=\\n',
          '--ignore-words-list=youn,unsupport,noe,cann',
          '--check-filenames',
          '--check-hidden'
        ]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--config=.flake8']
